### ISSUE TITLE
IDE SUPPORT

### ISSUE THREAD

**Issue by lobra07** [OpenNuvoton/N9H26_emWin_NonOS#1]
I'm wondering ,searching about the IDE that i can use except KEIL 
in folders i see GCC but is nu-eclipse support arm9

**Comment by kchuang1** [comment]
Hi,

Nu-Eclipse does not support arm9.
You can refere below document to install the Eclipse for arm9 development.
https://github.com/OpenNuvoton/N9H20_NonOS_BSP/blob/master/Documents/N9H20%20Eclipse%20User%20Manual.pdf

**Comment by lobra07** [comment]
AFTER I posted the question i tried and downloaded the nu-eclipse  and it dose compile the arm9 example codes without any error .. but i didn't try to flash them or anything

**Comment by kchuang1** [comment]
We still suggest you to follow the document to setup the environment for Eclipse which already test to work well on the device.
